elections/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = [
    url(r'^$', 'elections.views.elections_list', name='elections_list'),
    url(r'^(?P<election_id>[0-9]+)/$', 'elections.views.election', name='election'),
    url(r'^(?P<election_id>[0-9]+)/wannabe$', 'elections.views.wannabe', name='wannabe'),
    url(r'^(?P<election_id>[0-9]+)/wannabe_expert$', 'elections.views.wannabe_expert', name='wannabe_expert'),
    url(r'^(?P<election_id>[0-9]+)/dont_wannabe$', 'elections.views.dont_wannabe', name='dont_wannabe'),
    url(r'^(?P<election_id>[0-9]+)/dont_wannabe_expert$', 'elections.views.dont_wannabe_expert', name='dont_wannabe_expert'),

    url(r'^(?P<election_id>[0-9]+)/vote/(?P<nominee_id>[0-9]+)/$', 'elections.views.vote', name='vote'),
    url(r'^(?P<election_id>[0-9]+)/delegate/(?P<expert_id>[0-9]+)/$', 'elections.views.delegate', name='delegate'),

    url(r'^(?P<election_id>[0-9]+)/free_vote$', 'elections.views.free_vote', name='free_vote'),
    ]

oblako/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from registration.backends.hmac.views import RegistrationView
from extuser.forms import ExtUserRegistrationForm


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'oblako.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/register/$',
        RegistrationView.as_view(
            form_class=ExtUserRegistrationForm
        ),
        name='registration_register',
    ),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^accounts/profile/$', 'extuser.views.profile', name='profile'),
    url(r'^$', 'elections.views.elections_list', name='index'),
    url(r'^elections/', include('elections.urls')),
    url(r'^yandex-money-notice$', 'yandexmoney_notice.views.http_notification'),
)

elections/models.py
from django.conf import settings
from django.db import models

class Election(models.Model):
    nomination_name = models.CharField(max_length=200)
    def __str__(self):
        return self.nomination_name

    def i_am_nominee(self, user):
        try:
            Nominee.objects.get(nomination=self, nominee=user)
            return True
        except Nominee.DoesNotExist:
            return False
    def i_am_expert(self, user):
        try:
            ElectionExpert.objects.get(nomination=self, expert=user)
            return True
        except ElectionExpert.DoesNotExist:
            return False
    def wannabe(self, user):
        try:
            Nominee.objects.get(nomination=self, nominee=user)
            return # already nominee, do nothing
        except Nominee.DoesNotExist:
            n = Nominee(nomination=self, nominee=user)
            n.save()
    def wannabe_expert(self, user):
        try:
            ElectionExpert.objects.get(nomination=self, expert=user)
            return # already expert, do nothing
        except ElectionExpert.DoesNotExist:
            e = ElectionExpert(nomination=self, expert=user)
            e.save()
    def dont_wannabe(self, user):
        ElectionVote.objects.filter(nomination=self, is_delegated=False, vote=user).delete() # clear all votes for me
        try:
            n = Nominee.objects.get(nomination=self, nominee=user)
            n.delete()
        except Nominee.DoesNotExist:
            return # already not nominee, do nothing
    def dont_wannabe_expert(self, user):
        ElectionVote.objects.filter(nomination=self, is_delegated=True, vote=user).delete() # clear all delegations to me
        try:
            e = ElectionExpert.objects.get(nomination=self, expert=user)
            e.delete()
        except ElectionExpert.DoesNotExist:
            return # already not expert, do nothing

    def vote(self, nominee, user):
        ElectionVote.objects.filter(nomination = self, people = user).delete()
        v = ElectionVote(nomination = self, vote = nominee.nominee, is_delegated = False, people = user)
        v.save()
    def delegate(self, expert, user):
        ElectionVote.objects.filter(nomination = self, people = user).delete()
        v = ElectionVote(nomination = self, vote = expert.expert, is_delegated = True, people = user)
        v.save()

    def vote_is_free(self, user):
        v = ElectionVote.objects.filter(nomination=self, people=user)
        if len(v) == 0:
            return True
        else:
            return False
    def vote_is_delegated(self, user):
        v = ElectionVote.objects.filter(nomination=self, people=user)
        if len(v) == 1:
            return v[0].is_delegated
        return False
    def my_vote(self, user):
        v = ElectionVote.objects.filter(nomination=self, people=user)
        if len(v) == 1:
            return v[0].vote
        return ""
    def free_vote(self, user):
        ElectionVote.objects.filter(nomination = self, people = user).delete()

    def get_winner(self):
        result = (None, 0)
        current_nominees = Nominee.objects.filter(nomination = self)
        for cur_nominee in current_nominees:
            votes = cur_nominee.total_votes()
            if votes > result[1]:
                result = (cur_nominee.nominee, votes)

        return result
    def get_winner_name(self):
        return self.get_winner()[0]
    def get_winner_votes(self):
        return self.get_winner()[1]

class Nominee(models.Model):
    nomination = models.ForeignKey(Election)
    nominee = models.ForeignKey(settings.AUTH_USER_MODEL)
    def __str__(self):
        return str(self.nomination) + " / " + str(self.nominee)
    def total_votes(self):
        return self.direct_votes() + self.delegated_votes()
    def direct_votes(self):
        dv = ElectionVote.objects.filter(nomination=self.nomination, vote=self.nominee, is_delegated=False)
        return len(dv)
    def delegated_votes(self):
        result = 0
        all_experts = ElectionExpert.objects.filter(nomination=self.nomination)
        for expert in all_experts:
            if self.nomination.my_vote(expert.expert) == self.nominee: # TODO rename nomination.my_vote
                result += expert.delegated_votes()
        return result

class ElectionExpert(models.Model):
    nomination = models.ForeignKey(Election)
    expert = models.ForeignKey(settings.AUTH_USER_MODEL)
    def __str__(self):
        return str(self.nomination) + " / " + str(self.expert)
    def delegated_votes(self):
        dv = ElectionVote.objects.filter(nomination = self.nomination, is_delegated = True, vote = self.expert)
        return len(dv)
    def voted_for(self):
        v = ElectionVote.objects.filter(nomination = self.nomination, people = self.expert, is_delegated = False)
        if len(v) == 1:
            return v[0].vote
        return "not voted"


class ElectionVote(models.Model):
    nomination = models.ForeignKey(Election)
    people = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="people")
    is_delegated = models.BooleanField(default=False)
    vote = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="vote")
    def __str__(self):
        return str(self.nomination) + ": " + str(self.people) + self.str_delegated_or_voted() + str(self.vote)
    def str_delegated_or_voted(self):
        if self.is_delegated:
            return " delegate vote to "
        else:
            return " voted for "

elections/views.py
from django.shortcuts import render
from elections.models import Election, Nominee, ElectionExpert
from django.contrib.auth.decorators import login_required

def get_parameters(request, election_id):
    this_election = Election.objects.get(pk=election_id)
    return {
        "election": this_election, 
        "i_am_expert": this_election.i_am_expert(request.user),
        "i_am_nominee": this_election.i_am_nominee(request.user),
        "current_user": request.user,
        "vote_is_free": this_election.vote_is_free(request.user),
        "vote_is_delegated": this_election.vote_is_delegated(request.user),
        "my_vote": this_election.my_vote(request.user)
    }

# Create your views here.
@login_required
def elections_list(request):

    parameters = {"election_list": Election.objects.all()}
    return render(request, 'elections/elections.html', parameters)

@login_required
def election(request, election_id):
    return render(request, 'elections/election.html', get_parameters(request, election_id))

@login_required
def wannabe(request, election_id):
    this_election = Election.objects.get(pk=election_id)
    this_election.wannabe(request.user)

    return render(request, 'elections/election.html', get_parameters(request, election_id))

@login_required
def wannabe_expert(request, election_id):
    this_election = Election.objects.get(pk=election_id)
    this_election.wannabe_expert(request.user)

    return render(request, 'elections/election.html', get_parameters(request, election_id))

@login_required
def dont_wannabe(request, election_id):
    this_election = Election.objects.get(pk=election_id)
    this_election.dont_wannabe(request.user)

    return render(request, 'elections/election.html', get_parameters(request, election_id))

@login_required
def dont_wannabe_expert(request, election_id):
    this_election = Election.objects.get(pk=election_id)
    this_election.dont_wannabe_expert(request.user)

    return render(request, 'elections/election.html', get_parameters(request, election_id))

@login_required
def vote(request, election_id, nominee_id):
    this_election = Election.objects.get(pk=election_id)
    this_nominee = Nominee.objects.get(pk=nominee_id)
    this_election.vote(this_nominee, request.user)

    return render(request, 'elections/election.html', get_parameters(request, election_id))

@login_required
def delegate(request, election_id, expert_id):
    this_election = Election.objects.get(pk=election_id)
    if not this_election.i_am_expert(request.user): # don't use cascade vote delegation
        this_expert = ElectionExpert.objects.get(pk=expert_id)
        this_election.delegate(this_expert, request.user)

    return render(request, 'elections/election.html', get_parameters(request, election_id))

@login_required
def free_vote(request, election_id):
    this_election = Election.objects.get(pk=election_id)
    this_election.free_vote(request.user)

    return render(request, 'elections/election.html', get_parameters(request, election_id))

elections/templates/elections/election.html
{% extends "base.html" %}

{% block content %}
<h3><a href="{% url 'index' %}">К списку</a></h3>

<h3>Выборы {{ election }}</h4>

<p><h4>Кандидаты:</h4>
<table border="1">
<tr><td><b>Имя</b></td><td><b>Голосов</b></td><td><b></b></td></tr>
{% for nominee in election.nominee_set.all %}
<tr>
<td>{{ nominee.nominee }}</td>
<td>{{ nominee.total_votes }}</td><td>
<a href="{% url 'vote' election.id nominee.id %}">Проголосовать</a></td>
</tr>
{% endfor %}
</table>

{% if i_am_nominee %}
Я кандидат на этих выборах. <a href="{% url 'dont_wannabe' election.id %}">Перестать быть кандидатом</a>
{% else %}
<a href="{% url 'wannabe' election.id %}">Выдвинуться кандидатом</a>
{% endif %}
</p>

<p><h4>Эксперты:</h4>
<table border="1">
<tr><td><b>Имя</b></td><td><b>Голосов</b></td><td><b>Проголосовал за</b></td>
{% if not i_am_expert %}<td><b></b></td>{% endif %}
</tr>
{% for expert in election.electionexpert_set.all %}
<tr>
<td>{{ expert.expert }}</td>
<td>{{ expert.delegated_votes }}</td>
<td>{{ expert.voted_for }}</td>
{% if not i_am_expert %}<td><a href="{% url 'delegate' election.id expert.id %}">Делегировать</a></td>{% endif %}
</tr>
{% endfor %}
</table>

{% if i_am_expert %}
Я эксперт на этих выборах. <a href="{% url 'dont_wannabe_expert' election.id %}">Перестать быть экспертом</a>
{% else %}
<a href="{% url 'wannabe_expert' election.id %}">Заявиться экспертом</a>
{% endif %}
</p>

<p><h4>Мой голос</h4>
{% if vote_is_free %}
Свободен.
{% elif vote_is_delegated %}
Делегирован: {{ my_vote }}. (<a href="{% url 'free_vote' election.id %}">Отозвать</a>)
{% else %}
Отдан: {{ my_vote }}. (<a href="{% url 'free_vote' election.id %}">Отозвать</a>)
{% endif %}
</p>

{% endblock %}

elections/templates/elections/elections.html
{% extends "base.html" %}

{% block content %}

Список активных выборов:

<table border=1>
<tr>
<td>
<b>Выборы</b>
</td>
<td>
<b>Победитель</b>
</td>
<td>
<b>Голосов</b>
</td>
</tr>
{% for election in election_list %}
<tr>
<td>
<a href="/elections/{{ election.id }}/">{{ election }}</a>
</td>
<td>
{{ election.get_winner_name }}
</td>
<td>
{{ election.get_winner_votes }}
</td>
</tr>
{% endfor %}
</table>

{% endblock %}

elections/templates/elections/make_payment.html
{% extends "base.html" %}

{% block content %}

<iframe 
  frameborder="0" 
  allowtransparency="true" 
  scrolling="no" 
  src="https://money.yandex.ru/embed/shop.xml?account=41001550415485&quickpay=shop&payment-type-choice=on&writer=seller&targets=%D0%9D%D0%B0%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5&targets-hint=&default-sum=100&button-text=01&mail=on&successURL=https%3A%2F%2F127.0.0.1%2F"
  width="450" 
  height="198">
</iframe>

{% endblock %}